"""记忆接口"""

from typing import List, Optional, Protocol

from .entry import MemoryEntry


class Memory(Protocol):
    def store(self, entry: MemoryEntry): ...
    def retrieve(self, id: str) -> Optional[MemoryEntry]: ...
    def search(self, query: str, limit: int) -> List[MemoryEntry]: ...
    def get_all(self) -> List[MemoryEntry]: ...
    def delete(self, id: str) -> bool: ...
    def clear(self): ...
    def token_count(self) -> int: ...
    def size(self) -> int: ...
